FROM python:buster

RUN pip install buildbot-worker
RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN bash get-docker.sh

RUN mkdir -v bb-worker
WORKDIR bb-worker
RUN buildbot-worker create-worker worker 172.18.0.2 hex7-worker pass

CMD ["twistd", "-n", "-l", "-", "-y", "/bb-worker/worker/buildbot.tac"]

